# Manually triggered build action
name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build the package
      - name: Build Package
        run: scripts/build.sh

      # Upload build output
      - name: Upload Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: factorio-k2-steel-pipes.zip
          path: build/k2-steel-pipes_*.zip
